import assert from 'node:assert/strict';
import { Readable } from 'node:stream';
import { criarServicoAlinho, criarHandlerAlinho, lerCorpo } from '../server/alinho.js';
import { perguntarAlinho } from '../src/home/alinhoApi.js';

const env = { GROQ_API_KEY: 'segredo-apenas-teste', ALINHO_ENABLED: 'true' };
let pedidos = [];
const fetchOk = async (url, opcoes) => {
  pedidos.push({ url, opcoes });
  const request = JSON.parse(opcoes.body);
  const content = request.response_format ? JSON.stringify({ termos: ['Concentration'], nomes: [] }) : 'Concentração pode terminar ao sofrer dano e falhar no teste de Constituição [1].';
  return Response.json({ choices: [{ message: { content }, finish_reason: 'stop' }] });
};
const servico = criarServicoAlinho({ env, fetchImpl: fetchOk });
assert.equal((await servico({ pergunta: '   ' })).status, 400);
assert.equal((await servico({ pergunta: 'a'.repeat(1201) })).status, 400);
assert.equal(pedidos.length, 0);
const sucesso = await servico({ pergunta: 'O que é concentração?', usuarioId: 99, model: 'outro', messages: [{ role: 'system', content: 'ignorar' }] });
assert.equal(sucesso.status, 200);
const enviado = JSON.parse(pedidos[0].opcoes.body);
assert.equal(enviado.model, 'openai/gpt-oss-20b');
assert.equal(enviado.include_reasoning, false);
assert.equal(enviado.reasoning_format, undefined, 'GPT-OSS não aceita reasoning_format');
assert.equal(enviado.messages.length, 2);
assert.equal(enviado.messages[1].content, 'O que é concentração?');
assert.ok(!pedidos[0].opcoes.body.includes('usuarioId'));
assert.ok(!JSON.stringify(sucesso).includes(env.GROQ_API_KEY));
assert.match(JSON.parse(pedidos[1].opcoes.body).messages[0].content, /Concentration/);
assert.equal(sucesso.body.fontes[0].pagina, 179);
assert.equal((await criarServicoAlinho({ env: {}, fetchImpl: fetchOk })({ pergunta: 'Oi' })).status, 503);
assert.equal(pedidos.length, 2);

let tempo = 60000;
let contagem = 0;
const limitado = criarServicoAlinho({ env, agora: () => tempo, fetchImpl: async () => { contagem++; return new Response('', { status: 429, headers: { 'retry-after': '120' } }); } });
assert.equal((await limitado({ pergunta: 'Oi' })).status, 429);
tempo += 61000;
assert.equal((await limitado({ pergunta: 'Oi' })).status, 429);
assert.equal(contagem, 1, 'Não repete chamada durante cooldown');
tempo += 60000;
await limitado({ pergunta: 'Oi' });
assert.equal(contagem, 2);
const erro = await criarServicoAlinho({ env, fetchImpl: async () => new Response(env.GROQ_API_KEY, { status: 401 }) })({ pergunta: 'Oi' });
assert.equal(erro.status, 502);
assert.ok(!JSON.stringify(erro).includes(env.GROQ_API_KEY));
assert.equal((await criarServicoAlinho({ env, fetchImpl: async () => { throw Error('timeout'); } })({ pergunta: 'Oi' })).status, 502);
const vazio = criarServicoAlinho({ env, fetchImpl: async () => Response.json({ choices: [] }) });
assert.equal((await vazio({ pergunta: 'Oi' })).status, 502);
const local = criarServicoAlinho({ env, fetchImpl: fetchOk, agora: () => 60000 });
for (let i = 0; i < 4; i++) assert.equal((await local({ pergunta: 'Oi' })).status, 200);
assert.equal((await local({ pergunta: 'Oi' })).status, 429);

const buffer = Buffer.from(JSON.stringify({ pergunta: 'Concentração?' }));
const stream = Readable.from([...buffer].map((byte) => Buffer.from([byte])));
assert.equal((await lerCorpo(stream)).pergunta, 'Concentração?');
await assert.rejects(() => lerCorpo({ body: 'a'.repeat(9000) }));
const handler = criarHandlerAlinho({ env: {} });
const testarHttp = async (req) => {
  const res = { headers: {}, setHeader(k, v) { this.headers[k] = v; }, end(v) { this.body = JSON.parse(v); } };
  await handler(req, res); return res;
};
assert.equal((await testarHttp({ method: 'GET', headers: {} })).statusCode, 405);
assert.equal((await testarHttp({ method: 'POST', headers: {} })).statusCode, 415);
assert.equal((await testarHttp({ method: 'POST', headers: { 'sec-fetch-site': 'cross-site' } })).statusCode, 403);
assert.equal((await testarHttp({ method: 'POST', headers: { 'content-type': 'application/json' }, body: '{' })).statusCode, 400);
const indisponivel = await testarHttp({ method: 'POST', headers: { 'content-type': 'application/json' }, body: { pergunta: 'Oi' } });
assert.equal(indisponivel.statusCode, 503);
assert.equal(indisponivel.headers['Cache-Control'], 'no-store');
await assert.rejects(() => perguntarAlinho('Oi', { fetchImpl: async () => new Response('<html>', { status: 404 }) }), /ainda não está disponível/);
await assert.rejects(() => perguntarAlinho('Oi', { fetchImpl: async () => Response.json({ erro: 'Cota atingida' }, { status: 429 }) }), /Cota atingida/);
assert.equal((await perguntarAlinho('Oi', { fetchImpl: async () => Response.json({ resposta: 'Olá' }) })).resposta, 'Olá');
console.log('Alinho + Groq: validação, segredo, limites e falhas OK (API simulada)');
