import assert from 'node:assert/strict';
import { tokenVisivelNaNevoa, tokensDoObservador } from '../src/mesa/nevoa.js';
import { celulasVisiveisDoPonto } from '../src/mesa/paredes.js';
const token = {x:245,y:175};
const porta = {tipo:'porta',x1:140,y1:-1000,x2:140,y2:1000,aberta:false};
const contexto = {comoJogador:true,fogAtivo:true,gridSize:70,fogRevelado:new Set(['3,2'])};
const ver = aberta => celulasVisiveisDoPonto(35,175,420,70,[{...porta,aberta}]);
assert.equal(tokenVisivelNaNevoa(token,{...contexto,celulasVisiveis:ver(false)}),false);
assert.equal(tokenVisivelNaNevoa(token,{...contexto,celulasVisiveis:ver(true)}),true);
assert.equal(tokenVisivelNaNevoa(token,{...contexto,comoJogador:false,celulasVisiveis:ver(false)}),true);
assert.equal(tokenVisivelNaNevoa(token,{...contexto,fogAtivo:false,celulasVisiveis:new Set()}),true);
assert.equal(tokenVisivelNaNevoa(token,{...contexto,celulasVisiveis:null}),true);
assert.equal(tokenVisivelNaNevoa(token,{...contexto,celulasVisiveis:null,fogRevelado:new Set()}),false);
const fontes=[{fichaId:1,donoId:7},{fichaId:2,donoId:8},{fichaId:3,donoId:99},{donoId:7}];
assert.deepEqual(tokensDoObservador(fontes,'7'),[fontes[0]]);
assert.deepEqual(tokensDoObservador(fontes,''),[]);
const memoria = new Set(ver(true));
assert.ok(memoria.has('3,2'));
assert.equal(tokenVisivelNaNevoa(token,{...contexto,fogRevelado:memoria,celulasVisiveis:ver(false)}),false);
console.log('ok: névoa esconde criaturas, preserva terreno e isola observadores');
