export const PERICIAS_INFO = [
  { id: 'acrobacia', nome: 'Acrobacia', nomeEn: 'Acrobatics', attr: 'des' },
  { id: 'adestramento', nome: 'Adestramento', nomeEn: 'Animal Handling', attr: 'sab' },
  { id: 'arcanismo', nome: 'Arcanismo', nomeEn: 'Arcana', attr: 'int' },
  { id: 'atletismo', nome: 'Atletismo', nomeEn: 'Athletics', attr: 'for' },
  { id: 'atuacao', nome: 'Atuação', nomeEn: 'Performance', attr: 'car' },
  { id: 'enganacao', nome: 'Enganação', nomeEn: 'Deception', attr: 'car' },
  { id: 'furtividade', nome: 'Furtividade', nomeEn: 'Stealth', attr: 'des' },
  { id: 'historia', nome: 'História', nomeEn: 'History', attr: 'int' },
  { id: 'intimidacao', nome: 'Intimidação', nomeEn: 'Intimidation', attr: 'car' },
  { id: 'intuicao', nome: 'Intuição', nomeEn: 'Insight', attr: 'sab' },
  { id: 'investigacao', nome: 'Investigação', nomeEn: 'Investigation', attr: 'int' },
  { id: 'medicina', nome: 'Medicina', nomeEn: 'Medicine', attr: 'sab' },
  { id: 'natureza', nome: 'Natureza', nomeEn: 'Nature', attr: 'int' },
  { id: 'percepcao', nome: 'Percepção', nomeEn: 'Perception', attr: 'sab' },
  { id: 'persuasao', nome: 'Persuasão', nomeEn: 'Persuasion', attr: 'car' },
  { id: 'prestidigitacao', nome: 'Prestidigitação', nomeEn: 'Sleight of Hand', attr: 'des' },
  { id: 'religiao', nome: 'Religião', nomeEn: 'Religion', attr: 'int' },
  { id: 'sobrevivencia', nome: 'Sobrevivência', nomeEn: 'Survival', attr: 'sab' },
];

export const CLASSES_DND = [
  {
    id: 'barbaro',
    nome: 'Bárbaro',
    nomeEn: 'Barbarian',
    tag: 'SRD',
    icone: 'swords',
    papel: 'Combatente Físico / Tanque',
    dadoVida: 'd12',
    dadoVidaMax: 12,
    salvaguardas: ['for', 'con'],
    armaduras: ['Armaduras Leves', 'Armaduras Médias', 'Escudos'],
    armas: ['Armas Simples', 'Armas Marciais'],
    ferramentas: 'Nenhuma',
    qtdPericiasClasse: 2,
    opcoesPericias: ['adestramento', 'atletismo', 'intimidacao', 'natureza', 'percepcao', 'sobrevivencia'],
    descricao: 'Um guerreiro feroz impulsionado por uma fúria primal inabalável que resiste a danos devastadores.',
    habilidadesNivel1: [
      { nome: 'Fúria (Rage)', desc: 'Em batalha, você luta com ferocidade primal. Ganha vantagem em testes de Força e resistência a dano concussão, cortante e perfurante.' },
      { nome: 'Defesa Sem Armadura', desc: 'Enquanto não estiver usando armadura, sua CA é 10 + mod Destreza + mod Constituição.' },
    ],
    subclasses: [
      { nome: 'Caminho do Berserker', desc: 'Canaliza uma fúria cega que concede ataques adicionais como ação bônus.' },
      { nome: 'Caminho do Guerreiro Totêmico', desc: 'Adota o espírito de um animal totem (Urso, Águia, Lobo) para ganhar poderes místicos.' },
      { nome: 'Caminho do Zealot', desc: 'Alimentado pelo fervor divino de um deus da guerra e batalha.' },
    ],
    equipamentoInicial: {
      opcaoA: {
        nome: 'Pacote do Bárbaro Tradicional',
        itens: ['Machado Grande', 'Dois Machados de Arremesso', 'Pacote de Explorador', '4 Azagaias'],
        ataque: { nome: 'Machado Grande', acertoAttr: 'for', dano: '1d12', tipoDano: 'Cortante' },
      },
      opcaoB: {
        nome: 'Pacote do Duelista Ágil',
        itens: ['Espada Grande', 'Duas Espadas Curtas', 'Pacote de Aventureiro'],
        ataque: { nome: 'Espada Grande', acertoAttr: 'for', dano: '2d6', tipoDano: 'Cortante' },
      },
      ouroInicial: '2d4 * 10 (50 PO)',
      ouroValor: 50,
    },
  },
  {
    id: 'bardo',
    nome: 'Bardo',
    nomeEn: 'Bard',
    tag: 'SRD',
    icone: 'music_note',
    papel: 'Suporte / Conjurador / Perito',
    dadoVida: 'd8',
    dadoVidaMax: 8,
    salvaguardas: ['des', 'car'],
    armaduras: ['Armaduras Leves'],
    armas: ['Armas Simples', 'Bestas de mão', 'Espadas longas', 'Rapieiras', 'Espadas curtas'],
    ferramentas: 'Três instrumentos musicais à sua escolha',
    qtdPericiasClasse: 3,
    opcoesPericias: PERICIAS_INFO.map((p) => p.id),
    descricao: 'Um mestre inspirador que manipula a trama do multiverso através de palavras, música e magia fascinante.',
    habilidadesNivel1: [
      { nome: 'Conjuração (Carisma)', desc: 'Conhece truques e magias de bardo e usa Carisma como atributo de conjuração.' },
      { nome: 'Inspiração Bárdica (d6)', desc: 'Pode inspirar aliados com uma ação bônus, adicionando 1d6 a testes, rolagens de ataque ou dano.' },
    ],
    subclasses: [
      { nome: 'Colégio do Conhecimento (Lore)', desc: 'Domina vastas áreas do saber mundano e mágico, além de insultos cortantes.' },
      { nome: 'Colégio da Bravura (Valor)', desc: 'Incentiva a bravura marcial na linha de frente com armaduras médias e escudos.' },
      { nome: 'Colégio das Espadas (Swords)', desc: 'Um duelista acrobático e refinado que executa floreios mortais.' },
    ],
    equipamentoInicial: {
      opcaoA: {
        nome: 'Pacote do Menestrel Elegante',
        itens: ['Rapieira', 'Pacote de Diplomata', 'Alaúde', 'Armadura de Couro', 'Adaga'],
        ataque: { nome: 'Rapieira', acertoAttr: 'des', dano: '1d8', tipoDano: 'Perfurante' },
      },
      opcaoB: {
        nome: 'Pacote do Andarilho',
        itens: ['Espada Longa', 'Pacote de Artista', 'Flauta', 'Armadura de Couro', 'Adaga'],
        ataque: { nome: 'Espada Longa', acertoAttr: 'for', dano: '1d8', tipoDano: 'Cortante' },
      },
      ouroInicial: '5d4 * 10 (125 PO)',
      ouroValor: 125,
    },
  },
  {
    id: 'clerigo',
    nome: 'Clérigo',
    nomeEn: 'Cleric',
    tag: 'SRD',
    icone: 'flare',
    papel: 'Curandeiro / Conjurador Divino / Tanque',
    dadoVida: 'd8',
    dadoVidaMax: 8,
    salvaguardas: ['sab', 'car'],
    armaduras: ['Armaduras Leves', 'Armaduras Médias', 'Escudos'],
    armas: ['Armas Simples'],
    ferramentas: 'Nenhuma',
    qtdPericiasClasse: 2,
    opcoesPericias: ['historia', 'intuicao', 'medicina', 'persuasao', 'religiao'],
    descricao: 'Um campeão e canalizador do poder divino de uma divindade ou domínio cósmico.',
    habilidadesNivel1: [
      { nome: 'Conjuração Divina (Sabedoria)', desc: 'Prepara e conjura magias divinas baseadas na sua Sabedoria.' },
      { nome: 'Domínio Divino', desc: 'Escolhe um domínio (Vida, Luz, Guerra, etc.) que concede magias adicionais e bênçãos.' },
    ],
    subclasses: [
      { nome: 'Domínio da Vida', desc: 'Especialista em cura suprema e revitalização de companheiros.' },
      { nome: 'Domínio da Luz', desc: 'Invoca o fogo sagrado e radiância solar para queimar as trevas.' },
      { nome: 'Domínio da Guerra', desc: 'Um sacerdote guerreiro empunhando armas marciais e armaduras pesadas.' },
      { nome: 'Domínio da Tempestade', desc: 'Canaliza a fúria dos trovões e relâmpagos das divindades marítimas.' },
    ],
    equipamentoInicial: {
      opcaoA: {
        nome: 'Pacote do Guardião da Fé',
        itens: ['Maça', 'Cota de Escamas', 'Besta Leve e 20 Virotes', 'Escudo', 'Símbolo Sagrado', 'Pacote de Sacerdote'],
        ataque: { nome: 'Maça', acertoAttr: 'for', dano: '1d6', tipoDano: 'Concussão' },
      },
      opcaoB: {
        nome: 'Pacote do Cruzado',
        itens: ['Martelo de Guerra', 'Cota de Malha (se proficiente)', 'Escudo', 'Símbolo Sagrado', 'Pacote de Explorador'],
        ataque: { nome: 'Martelo de Guerra', acertoAttr: 'for', dano: '1d8', tipoDano: 'Concussão' },
      },
      ouroInicial: '5d4 * 10 (125 PO)',
      ouroValor: 125,
    },
  },
  {
    id: 'druida',
    nome: 'Druida',
    nomeEn: 'Druid',
    tag: 'SRD',
    icone: 'nature',
    papel: 'Metamorfo / Conjurador Primal',
    dadoVida: 'd8',
    dadoVidaMax: 8,
    salvaguardas: ['int', 'sab'],
    armaduras: ['Armaduras Leves', 'Armaduras Médias', 'Escudos (não-metálicos)'],
    armas: ['Clavas', 'Adagas', 'Dardos', 'Azagaias', 'Maças', 'Bordões', 'Cimitarras', 'Foices', 'Fundas', 'Lanças'],
    ferramentas: 'Kit de Herbalismo',
    qtdPericiasClasse: 2,
    opcoesPericias: ['adestramento', 'arcanismo', 'intuicao', 'medicina', 'natureza', 'percepcao', 'religiao', 'sobrevivencia'],
    descricao: 'Um guardião dos segredos ancestrais da natureza capaz de se transformar em feras majestosas.',
    habilidadesNivel1: [
      { nome: 'Conjuração Druídica (Sabedoria)', desc: 'Canaliza o poder dos elementos, plantas e animais.' },
      { nome: 'Druídico', desc: 'Você conhece o Druídico, a linguagem secreta dos druidas.' },
    ],
    subclasses: [
      { nome: 'Círculo da Lua', desc: 'Focado em formas selvagens brutais e metamorfose em combate de elite.' },
      { nome: 'Círculo da Terra', desc: 'Místicos que aprofundam a conjuração com base em seu bioma natal.' },
      { nome: 'Círculo dos Esporos', desc: 'Utiliza fungos e esporos necróticos para reviver servos e causar dano.' },
    ],
    equipamentoInicial: {
      opcaoA: {
        nome: 'Pacote do Guardião Silvestre',
        itens: ['Escudo de Madeira', 'Cimitarra', 'Armadura de Couro', 'Pacote de Explorador', 'Foco Druídico'],
        ataque: { nome: 'Cimitarra', acertoAttr: 'des', dano: '1d6', tipoDano: 'Cortante' },
      },
      opcaoB: {
        nome: 'Pacote do Eremita',
        itens: ['Bordão', 'Armadura de Couro', 'Kit de Herbalismo', 'Foco Druídico'],
        ataque: { nome: 'Bordão', acertoAttr: 'for', dano: '1d6', tipoDano: 'Concussão' },
      },
      ouroInicial: '2d4 * 10 (50 PO)',
      ouroValor: 50,
    },
  },
  {
    id: 'guerreiro',
    nome: 'Guerreiro',
    nomeEn: 'Fighter',
    tag: 'SRD',
    icone: 'shield',
    papel: 'Mestre de Armas / Combatente Frontal',
    dadoVida: 'd10',
    dadoVidaMax: 10,
    salvaguardas: ['for', 'con'],
    armaduras: ['Todas as Armaduras', 'Escudos'],
    armas: ['Armas Simples', 'Armas Marciais'],
    ferramentas: 'Nenhuma',
    qtdPericiasClasse: 2,
    opcoesPericias: ['acrobacia', 'adestramento', 'atletismo', 'historia', 'intuicao', 'intimidacao', 'percepcao', 'sobrevivencia'],
    descricao: 'Um especialista supremo no domínio tático de armas, armaduras e manobras de combate.',
    habilidadesNivel1: [
      { nome: 'Estilo de Luta', desc: 'Adota uma especialização de combate (Arquearia, Defesa, Duelismo, etc.).' },
      { nome: 'Retomar o Fôlego (Second Wind)', desc: 'Uma vez por descanso curto, recupera 1d10 + nível em pontos de vida como ação bônus.' },
    ],
    subclasses: [
      { nome: 'Campeão (Champion)', desc: 'Aperfeiçoamento físico que alcança Acertos Críticos em 19 e 20.' },
      { nome: 'Mestre de Batalha (Battle Master)', desc: 'Estudioso de manobras táticas de precisão com dados de superioridade (d8).' },
      { nome: 'Cavaleiro Arcano (Eldritch Knight)', desc: 'Combina maestria com lâminas e magias de abjuração e evocação.' },
    ],
    equipamentoInicial: {
      opcaoA: {
        nome: 'Pacote do Cavaleiro de Infantaria',
        itens: ['Cota de Malha', 'Espada Longa', 'Escudo', 'Besta Leve com 20 virotes', 'Pacote de Aventureiro'],
        ataque: { nome: 'Espada Longa', acertoAttr: 'for', dano: '1d8', tipoDano: 'Cortante' },
      },
      opcaoB: {
        nome: 'Pacote do Atirador de Elite / Duelista',
        itens: ['Armadura de Couro Batido', 'Arco Longo com 20 Flechas', 'Duas Espadas Curtas', 'Pacote de Explorador'],
        ataque: { nome: 'Arco Longo', acertoAttr: 'des', dano: '1d8', tipoDano: 'Perfurante' },
      },
      ouroInicial: '5d4 * 10 (125 PO)',
      ouroValor: 125,
    },
  },
  {
    id: 'monge',
    nome: 'Monge',
    nomeEn: 'Monk',
    tag: 'SRD',
    icone: 'sports_martial_arts',
    papel: 'Combatente Desarmado / Mobilidade',
    dadoVida: 'd8',
    dadoVidaMax: 8,
    salvaguardas: ['for', 'des'],
    armaduras: ['Nenhuma'],
    armas: ['Armas Simples', 'Espadas Curtas'],
    ferramentas: 'Um tipo de ferramenta de artesão ou instrumento musical',
    qtdPericiasClasse: 2,
    opcoesPericias: ['acrobacia', 'atletismo', 'historia', 'intuicao', 'religiao', 'furtividade'],
    descricao: 'Um praticante de artes marciais que domina a energia interna do Ki para desferir golpes relâmpago.',
    habilidadesNivel1: [
      { nome: 'Defesa Sem Armadura', desc: 'Sem armadura e sem escudo, sua CA é 10 + mod Destreza + mod Sabedoria.' },
      { nome: 'Artes Marciais', desc: 'Permite usar Destreza para ataques desarmados (1d4 de dano) e atacar com ação bônus.' },
    ],
    subclasses: [
      { nome: 'Caminho da Mão Aberta', desc: 'Manipula o Ki dos inimigos para derrubá-los, empurrá-los e paralisá-los.' },
      { nome: 'Caminho das Sombras', desc: 'Ninjas místicos que se teletransportam através da escuridão.' },
      { nome: 'Caminho dos Quatro Elementos', desc: 'Canaliza o Ki em rajadas de fogo, ar, água e terra.' },
    ],
    equipamentoInicial: {
      opcaoA: {
        nome: 'Pacote do Acólito Marcial',
        itens: ['Espada Curta', 'Pacote de Aventureiro', '10 Dardos'],
        ataque: { nome: 'Espada Curta', acertoAttr: 'des', dano: '1d6', tipoDano: 'Perfurante' },
      },
      opcaoB: {
        nome: 'Pacote do Mestre do Cajado',
        itens: ['Bordão', 'Pacote de Explorador', '10 Dardos'],
        ataque: { nome: 'Bordão Marcial', acertoAttr: 'des', dano: '1d6', tipoDano: 'Concussão' },
      },
      ouroInicial: '5d4 (12 PO)',
      ouroValor: 12,
    },
  },
  {
    id: 'paladino',
    nome: 'Paladino',
    nomeEn: 'Paladin',
    tag: 'SRD',
    icone: 'security',
    papel: 'Tanque Sagrado / Dano Radiante / Líder',
    dadoVida: 'd10',
    dadoVidaMax: 10,
    salvaguardas: ['sab', 'car'],
    armaduras: ['Todas as Armaduras', 'Escudos'],
    armas: ['Armas Simples', 'Armas Marciais'],
    ferramentas: 'Nenhuma',
    qtdPericiasClasse: 2,
    opcoesPericias: ['atletismo', 'intuicao', 'intimidacao', 'medicina', 'persuasao', 'religiao'],
    descricao: 'Um cavaleiro consagrado por um juramento sagrado inquebrável que aniquila o mal com destruição divina.',
    habilidadesNivel1: [
      { nome: 'Sentido Divino', desc: 'Detecta a presença de celestiais, ínferos, mortos-vivos e locais sagrados.' },
      { nome: 'Cura pelas Mãos (Lay on Hands)', desc: 'Possui uma reserva de cura igual a 5 x nível de paladino para restaurar aliados.' },
    ],
    subclasses: [
      { nome: 'Juramento de Devoção', desc: 'O ideal do cavaleiro de armadura brilhante, justiça e honra pura.' },
      { nome: 'Juramento dos Anciões', desc: 'Guardiões da luz, vida e beleza do mundo natural com poderes feéricos.' },
      { nome: 'Juramento de Vingança', desc: 'Punição implacável contra vilões hediondos.' },
    ],
    equipamentoInicial: {
      opcaoA: {
        nome: 'Pacote do Cruzado Sagrado',
        itens: ['Espada Longa', 'Escudo', '5 Azagaias', 'Cota de Malha', 'Símbolo Sagrado', 'Pacote de Sacerdote'],
        ataque: { nome: 'Espada Longa', acertoAttr: 'for', dano: '1d8', tipoDano: 'Cortante' },
      },
      opcaoB: {
        nome: 'Pacote do Paladino Vorpal',
        itens: ['Espadão de Duas Mãos', '5 Azagaias', 'Cota de Malha', 'Símbolo Sagrado', 'Pacote de Explorador'],
        ataque: { nome: 'Espadão', acertoAttr: 'for', dano: '2d6', tipoDano: 'Cortante' },
      },
      ouroInicial: '5d4 * 10 (125 PO)',
      ouroValor: 125,
    },
  },
  {
    id: 'patrulheiro',
    nome: 'Patrulheiro',
    nomeEn: 'Ranger',
    tag: 'SRD',
    icone: 'nature_people',
    papel: 'Atirador / Rastreador / Sobrevivente',
    dadoVida: 'd10',
    dadoVidaMax: 10,
    salvaguardas: ['for', 'des'],
    armaduras: ['Armaduras Leves', 'Armaduras Médias', 'Escudos'],
    armas: ['Armas Simples', 'Armas Marciais'],
    ferramentas: 'Nenhuma',
    qtdPericiasClasse: 3,
    opcoesPericias: ['adestramento', 'atletismo', 'intuicao', 'investigacao', 'natureza', 'percepcao', 'furtividade', 'sobrevivencia'],
    descricao: 'Um caçador implacável das fronteiras selvagens que vigia as ameaças invisíveis da natureza.',
    habilidadesNivel1: [
      { nome: 'Inimigo Favorito', desc: 'Possui estudo e vantagens táticas contra tipos específicos de criaturas.' },
      { nome: 'Explorador Natural', desc: 'Mestre da navegação em terrenos selvagens com benefícios de viagem.' },
    ],
    subclasses: [
      { nome: 'Caçador (Hunter)', desc: 'Técnicas especializadas para abater gigantes, hordas ou presas colossais.' },
      { nome: 'Mestre das Feras (Beast Master)', desc: 'Forma um vínculo psíquico e de batalha eterno com um companheiro animal.' },
      { nome: 'Andarilho do Horizonte (Horizon Walker)', desc: 'Guardião dos portais planares com mobilidade dimensional.' },
    ],
    equipamentoInicial: {
      opcaoA: {
        nome: 'Pacote do Arqueiro das Matas',
        itens: ['Cota de Escamas', 'Duas Espadas Curtas', 'Arco Longo com 20 flechas', 'Pacote de Explorador'],
        ataque: { nome: 'Arco Longo', acertoAttr: 'des', dano: '1d8', tipoDano: 'Perfurante' },
      },
      opcaoB: {
        nome: 'Pacote do Rastreador de Masmorra',
        itens: ['Armadura de Couro', 'Duas Cimitarras', 'Arco Curto com 20 flechas', 'Pacote de Aventureiro'],
        ataque: { nome: 'Cimitarra', acertoAttr: 'des', dano: '1d6', tipoDano: 'Cortante' },
      },
      ouroInicial: '5d4 * 10 (125 PO)',
      ouroValor: 125,
    },
  },
  {
    id: 'ladino',
    nome: 'Ladino',
    nomeEn: 'Rogue',
    tag: 'SRD',
    icone: 'vpn_key',
    papel: 'Especialista em Furtividade / Dano Crítico',
    dadoVida: 'd8',
    dadoVidaMax: 8,
    salvaguardas: ['des', 'int'],
    armaduras: ['Armaduras Leves'],
    armas: ['Armas Simples', 'Bestas de Mão', 'Espadas Longas', 'Rapieiras', 'Espadas Curtas'],
    ferramentas: 'Ferramentas de Ladrão (Thieves\' Tools)',
    qtdPericiasClasse: 4,
    opcoesPericias: ['acrobacia', 'atletismo', 'enganacao', 'intuicao', 'intimidacao', 'investigacao', 'percepcao', 'atuacao', 'persuasao', 'prestidigitacao', 'furtividade'],
    descricao: 'Um mestre da astúcia, precisão mortal e infiltração que ataca com o Ataque Furtivo letal.',
    habilidadesNivel1: [
      { nome: 'Especialização (Expertise)', desc: 'Dobra o bônus de proficiência em 2 perícias selecionadas ou ferramentas de ladrão.' },
      { nome: 'Ataque Furtivo (Sneak Attack - 1d6)', desc: 'Causa 1d6 de dano adicional uma vez por turno quando tem vantagem no ataque ou aliado próximo.' },
      { nome: 'Gíria de Ladrão (Thieves\' Cant)', desc: 'Um dialeto secreto de símbolos e palavras de duplo sentido.' },
    ],
    subclasses: [
      { nome: 'Assassino (Assassin)', desc: 'Mestre dos disfarces, venenos e ataques surpresa devastadores.' },
      { nome: 'Ladrão (Thief)', desc: 'Agilidade extraordinária para escalar, desarmar armadilhas com ação bônus e usar itens mágicos.' },
      { nome: 'Trapaceiro Arcano (Arcane Trickster)', desc: 'Combina furtividade com magias de ilusão e encantamento.' },
    ],
    equipamentoInicial: {
      opcaoA: {
        nome: 'Pacote do Espião das Sombras',
        itens: ['Rapieira', 'Arco Curto com 20 flechas', 'Pacote de Assaltante', 'Armadura de Couro', 'Duas Adagas', 'Ferramentas de Ladrão'],
        ataque: { nome: 'Rapieira', acertoAttr: 'des', dano: '1d8', tipoDano: 'Perfurante' },
      },
      opcaoB: {
        nome: 'Pacote do Duelista Clandestino',
        itens: ['Duas Espadas Curtas', 'Pacote de Explorador', 'Armadura de Couro', 'Duas Adagas', 'Ferramentas de Ladrão'],
        ataque: { nome: 'Espada Curta', acertoAttr: 'des', dano: '1d6', tipoDano: 'Perfurante' },
      },
      ouroInicial: '4d4 * 10 (100 PO)',
      ouroValor: 100,
    },
  },
  {
    id: 'feiticeiro',
    nome: 'Feiticeiro',
    nomeEn: 'Sorcerer',
    tag: 'SRD',
    icone: 'local_fire_department',
    papel: 'Conjurador Inato / Metamagia',
    dadoVida: 'd6',
    dadoVidaMax: 6,
    salvaguardas: ['con', 'car'],
    armaduras: ['Nenhuma'],
    armas: ['Adagas', 'Dardos', 'Fundas', 'Bordões', 'Bestas Leves'],
    ferramentas: 'Nenhuma',
    qtdPericiasClasse: 2,
    opcoesPericias: ['arcanismo', 'enganacao', 'intuicao', 'intimidacao', 'persuasao', 'religiao'],
    descricao: 'Um canalizador nato que nasceu com a magia pulsando em seu próprio sangue ou linhagem cósmica.',
    habilidadesNivel1: [
      { nome: 'Conjuração Inata (Carisma)', desc: 'Manipula feitiços poderosos originados de sua centelha interior.' },
      { nome: 'Origem da Feitiçaria', desc: 'Escolhe a fonte do seu poder inato (Linhagem Dracônica, Magia Selvagem, etc.).' },
    ],
    subclasses: [
      { nome: 'Linhagem Dracônica', desc: 'Pele escamosa que concede CA natural 13 + Des e afinidade com elementos de dragão.' },
      { nome: 'Magia Selvagem', desc: 'Magia caótica imprevisível com surtos de magia selvagem.' },
      { nome: 'Alma Divina', desc: 'Tocado pela centelha dos céus, com acesso à lista de magias de clérigo.' },
    ],
    equipamentoInicial: {
      opcaoA: {
        nome: 'Pacote do Prodígio Arcano',
        itens: ['Besta Leve com 20 virotes', 'Foco Arcano (Orbe)', 'Pacote de Aventureiro', 'Duas Adagas'],
        ataque: { nome: 'Adaga', acertoAttr: 'des', dano: '1d4', tipoDano: 'Perfurante' },
      },
      opcaoB: {
        nome: 'Pacote do Erudito Itinerante',
        itens: ['Bordão', 'Bolsa de Componentes', 'Pacote de Explorador', 'Duas Adagas'],
        ataque: { nome: 'Bordão', acertoAttr: 'for', dano: '1d6', tipoDano: 'Concussão' },
      },
      ouroInicial: '3d4 * 10 (75 PO)',
      ouroValor: 75,
    },
  },
  {
    id: 'bruxo',
    nome: 'Bruxo',
    nomeEn: 'Warlock',
    tag: 'SRD',
    icone: 'visibility',
    papel: 'Conjurador de Pacto / Disparo Místico',
    dadoVida: 'd8',
    dadoVidaMax: 8,
    salvaguardas: ['sab', 'car'],
    armaduras: ['Armaduras Leves'],
    armas: ['Armas Simples'],
    ferramentas: 'Nenhuma',
    qtdPericiasClasse: 2,
    opcoesPericias: ['arcanismo', 'enganacao', 'historia', 'intimidacao', 'investigacao', 'natureza', 'religiao'],
    descricao: 'Um conjurador que forjou um pacto secreto com uma entidade sobrenatural extraordinária.',
    habilidadesNivel1: [
      { nome: 'Patrono Sobrenatural', desc: 'Conectado a um ser de outro mundo (Corruptor, Arquifada, Grande Antigo).' },
      { nome: 'Magia de Pacto (Carisma)', desc: 'Seus espaços de magia sempre são conjurados no nível mais alto e recarregam em descansos curtos.' },
    ],
    subclasses: [
      { nome: 'O Corruptor (Fiend)', desc: 'Pacto infernal que concede vigor temporário ao matar inimigos e bolas de fogo.' },
      { nome: 'O Grande Antigo (Great Old One)', desc: 'Pacto com seres cósmicos que concede telepatia mental e distorções mentais.' },
      { nome: 'A Arquifada (Archfey)', desc: 'Encantos feéricos capazes de fascinar e aterrorizar os presentes.' },
      { nome: 'A Lâmina Maldita (Hexblade)', desc: 'Empunha armas vinculadas ao Carisma com maldições mortais.' },
    ],
    equipamentoInicial: {
      opcaoA: {
        nome: 'Pacote do Ocultista das Trevas',
        itens: ['Besta Leve com 20 virotes', 'Foco Arcano', 'Pacote de Estudioso', 'Armadura de Couro', 'Duas Adagas'],
        ataque: { nome: 'Adaga', acertoAttr: 'des', dano: '1d4', tipoDano: 'Perfurante' },
      },
      opcaoB: {
        nome: 'Pacote do Pactuário Bélico',
        itens: ['Lança Simples', 'Foco Arcano', 'Pacote de Aventureiro', 'Armadura de Couro', 'Duas Adagas'],
        ataque: { nome: 'Lança', acertoAttr: 'for', dano: '1d6', tipoDano: 'Perfurante' },
      },
      ouroInicial: '4d4 * 10 (100 PO)',
      ouroValor: 100,
    },
  },
  {
    id: 'mago',
    nome: 'Mago',
    nomeEn: 'Wizard',
    tag: 'SRD',
    icone: 'auto_stories',
    papel: 'Mestre da Magia Arcana / Versatilidade',
    dadoVida: 'd6',
    dadoVidaMax: 6,
    salvaguardas: ['int', 'sab'],
    armaduras: ['Nenhuma'],
    armas: ['Adagas', 'Dardos', 'Fundas', 'Bordões', 'Bestas Leves'],
    ferramentas: 'Nenhuma',
    qtdPericiasClasse: 2,
    opcoesPericias: ['arcanismo', 'historia', 'intuicao', 'investigacao', 'medicina', 'religiao'],
    descricao: 'Um acadêmico supremo das artes arcanas que registra feitiços lendários em seu grimório ancestral.',
    habilidadesNivel1: [
      { nome: 'Conjuração Arcana (Inteligência)', desc: 'Estuda e prepara magias do seu Grimório utilizando sua Inteligência.' },
      { nome: 'Recuperação Arcana', desc: 'Uma vez por dia em descanso curto, recupera espaços de magia gastos.' },
      { nome: 'Grimório', desc: 'Contém 6 magias de 1º nível à sua escolha.' },
    ],
    subclasses: [
      { nome: 'Escola de Evocação', desc: 'Especialista em magias destrutivas elementais sem atingir aliados.' },
      { nome: 'Escola de Abjuração', desc: 'Cria barreiras arcanas protetoras em volta de si e de aliados.' },
      { nome: 'Escola de Necromancia', desc: 'Drena a energia vital dos inimigos e anima servos esqueléticos.' },
      { nome: 'Escola de Adivinhação', desc: 'Muda o destino manipulando dados de presságio (Portent).' },
    ],
    equipamentoInicial: {
      opcaoA: {
        nome: 'Pacote do Erudito Supremo',
        itens: ['Bordão', 'Grimório com 6 magias', 'Foco Arcano (Varinha)', 'Pacote de Estudioso'],
        ataque: { nome: 'Bordão', acertoAttr: 'for', dano: '1d6', tipoDano: 'Concussão' },
      },
      opcaoB: {
        nome: 'Pacote do Pesquisador Prático',
        itens: ['Adaga', 'Grimório com 6 magias', 'Bolsa de Componentes', 'Pacote de Explorador'],
        ataque: { nome: 'Adaga', acertoAttr: 'des', dano: '1d4', tipoDano: 'Perfurante' },
      },
      ouroInicial: '4d4 * 10 (100 PO)',
      ouroValor: 100,
    },
  },
  {
    id: 'artifice',
    nome: 'Artífice',
    nomeEn: 'Artificer',
    tag: '2024',
    icone: 'precision_manufacturing',
    papel: 'Inventor Mágico / Infusões / Suporte',
    dadoVida: 'd8',
    dadoVidaMax: 8,
    salvaguardas: ['con', 'int'],
    armaduras: ['Armaduras Leves', 'Armaduras Médias', 'Escudos'],
    armas: ['Armas Simples', 'Bestas de Mão'],
    ferramentas: 'Ferramentas de Ladrão, Ferramentas de Latoeiro',
    qtdPericiasClasse: 2,
    opcoesPericias: ['arcanismo', 'historia', 'investigacao', 'medicina', 'natureza', 'percepcao', 'prestidigitacao'],
    descricao: 'Mestres da invenção que fundem ciência arcana com engenhocas e infusões mágicas.',
    habilidadesNivel1: [
      { nome: 'Engenhocaria Mágica', desc: 'Infunde propriedades mágicas menores em objetos mundanos.' },
      { nome: 'Conjuração (Inteligência)', desc: 'Usa ferramentas de artesão como foco para canalizar feitiços inteligentes.' },
    ],
    subclasses: [
      { nome: 'Armeiro (Armorer)', desc: 'Cria uma armadura arcana energizada como uma segunda pele.' },
      { nome: 'Alquimista (Alchemist)', desc: 'Fabrica elixires experimentais e infusões regenerativas.' },
      { nome: 'Artilheiro (Artillerist)', desc: 'Empunha canhões arcanos ambulantes de alta destruição.' },
    ],
    equipamentoInicial: {
      opcaoA: {
        nome: 'Pacote do Inventor Bélico',
        itens: ['Besta Leve com 20 virotes', 'Armadura de Couro Batido', 'Ferramentas de Latoeiro', 'Pacote de Explorador'],
        ataque: { nome: 'Besta Leve', acertoAttr: 'des', dano: '1d8', tipoDano: 'Perfurante' },
      },
      opcaoB: {
        nome: 'Pacote do Artífice de Campo',
        itens: ['Duas Adagas', 'Armadura de Couro', 'Ferramentas de Ladrão', 'Pacote de Aventureiro'],
        ataque: { nome: 'Adaga', acertoAttr: 'des', dano: '1d4', tipoDano: 'Perfurante' },
      },
      ouroInicial: '5d4 * 10 (125 PO)',
      ouroValor: 125,
    },
  },
];

export const ESPECIES_DND = [
  {
    id: 'humano',
    nome: 'Humano',
    nomeEn: 'Human',
    tag: 'SRD',
    icone: 'person',
    tamanho: 'Médio',
    deslocamento: '30ft (9m)',
    deslocamentoNum: 30,
    visaoEscuro: false,
    bonusAtributoFixo: { for: 1, des: 1, con: 1, int: 1, sab: 1, car: 1 },
    bonusDesc: '+1 em todos os 6 atributos (ou +2/+1 no formato flexível)',
    idiomas: ['Comum', 'Um idioma adicional à escolha'],
    traços: [
      { nome: 'Versatilidade Suprema', desc: 'Humanos se adaptam rapidamente a qualquer clima, cultura e profissão.' },
      { nome: 'Ambição Sem Limites', desc: 'Aprendizado rápido em línguas e habilidades.' },
    ],
    periciasConcedidas: [],
  },
  {
    id: 'alto_elfo',
    nome: 'Alto Elfo',
    nomeEn: 'High Elf',
    tag: 'SRD',
    icone: 'psychology',
    tamanho: 'Médio',
    deslocamento: '30ft (9m)',
    deslocamentoNum: 30,
    visaoEscuro: true,
    bonusAtributoFixo: { des: 2, int: 1 },
    bonusDesc: '+2 Destreza, +1 Inteligência',
    idiomas: ['Comum', 'Élfico', 'Um idioma extra'],
    traços: [
      { nome: 'Visão no Escuro (60ft)', desc: 'Enxerga na penumbra e escuridão até 18 metros.' },
      { nome: 'Sentidos Aguçados', desc: 'Proficiência nata na perícia Percepção.' },
      { nome: 'Ancestralidade Feérica', desc: 'Vantagem em salvaguardas contra ser enfeitiçado e imunidade ao sono mágico.' },
      { nome: 'Truque de Mago', desc: 'Conhece 1 truque da lista de magias de mago (ex: Prestidigitação, Raio de Fogo).' },
      { nome: 'Transe', desc: 'Descansa profundamente em apenas 4 horas diárias meditando.' },
    ],
    periciasConcedidas: ['percepcao'],
  },
  {
    id: 'elfo_floresta',
    nome: 'Elfo da Floresta',
    nomeEn: 'Wood Elf',
    tag: 'SRD',
    icone: 'forest',
    tamanho: 'Médio',
    deslocamento: '35ft (10.5m)',
    deslocamentoNum: 35,
    visaoEscuro: true,
    bonusAtributoFixo: { des: 2, sab: 1 },
    bonusDesc: '+2 Destreza, +1 Sabedoria',
    idiomas: ['Comum', 'Élfico'],
    traços: [
      { nome: 'Pés Ligeiros', desc: 'Seu deslocamento base aumenta para 35 pés (10,5m).' },
      { nome: 'Máscara da Natureza', desc: 'Pode se esconder mesmo quando apenas levemente obscurecido por folhagem, chuva ou névoa.' },
      { nome: 'Sentidos Aguçados', desc: 'Proficiência em Percepção.' },
      { nome: 'Ancestralidade Feérica', desc: 'Imune a sono mágico e vantagem contra encantos.' },
    ],
    periciasConcedidas: ['percepcao'],
  },
  {
    id: 'drow',
    nome: 'Elfo Negro (Drow)',
    nomeEn: 'Drow Elf',
    tag: 'SRD',
    icone: 'dark_mode',
    tamanho: 'Médio',
    deslocamento: '30ft (9m)',
    deslocamentoNum: 30,
    visaoEscuro: true,
    bonusAtributoFixo: { des: 2, car: 1 },
    bonusDesc: '+2 Destreza, +1 Carisma',
    idiomas: ['Comum', 'Élfico', 'Subterrâneo'],
    traços: [
      { nome: 'Visão no Escuro Superior (120ft)', desc: 'Enxerga na escuridão total até 36 metros.' },
      { nome: 'Magia Drow', desc: 'Conhece o truque Luzes Dançantes. No nível 3 ganha Fogo das Fadas e nível 5 Escuridão.' },
      { nome: 'Sensibilidade à Luz Solar', desc: 'Desvantagem em ataques se você ou o alvo estiver sob luz solar direta.' },
    ],
    periciasConcedidas: ['percepcao'],
  },
  {
    id: 'anao_colina',
    nome: 'Anão da Colina',
    nomeEn: 'Hill Dwarf',
    tag: 'SRD',
    icone: 'shield',
    tamanho: 'Médio',
    deslocamento: '25ft (7.5m)',
    deslocamentoNum: 25,
    visaoEscuro: true,
    bonusAtributoFixo: { con: 2, sab: 1 },
    bonusDesc: '+2 Constituição, +1 Sabedoria',
    idiomas: ['Comum', 'Anão'],
    traços: [
      { nome: 'Tenacidade Anã', desc: 'Seu PV máximo aumenta em +1 por nível permanentemente.' },
      { nome: 'Resiliência Anã', desc: 'Vantagem em salvaguardas contra veneno e resistência a dano de veneno.' },
      { nome: 'Especialização em Rochas', desc: 'Dobra proficiência em testes de História sobre alvenaria e rochas.' },
    ],
    periciasConcedidas: [],
  },
  {
    id: 'anao_montanha',
    nome: 'Anão da Montanha',
    nomeEn: 'Mountain Dwarf',
    tag: 'SRD',
    icone: 'hardware',
    tamanho: 'Médio',
    deslocamento: '25ft (7.5m)',
    deslocamentoNum: 25,
    visaoEscuro: true,
    bonusAtributoFixo: { for: 2, con: 2 },
    bonusDesc: '+2 Força, +2 Constituição',
    idiomas: ['Comum', 'Anão'],
    traços: [
      { nome: 'Treinamento com Armaduras Anãs', desc: 'Proficiência nata com Armaduras Leves e Armaduras Médias.' },
      { nome: 'Resiliência Anã', desc: 'Vantagem contra veneno e resistência a dano de veneno.' },
      { nome: 'Visão no Escuro (60ft)', desc: 'Enxerga na escuridão até 18 metros.' },
    ],
    periciasConcedidas: [],
  },
  {
    id: 'halfling',
    nome: 'Halfling Pés-Leves',
    nomeEn: 'Lightfoot Halfling',
    tag: 'SRD',
    icone: 'directions_walk',
    tamanho: 'Pequeno',
    deslocamento: '25ft (7.5m)',
    deslocamentoNum: 25,
    visaoEscuro: false,
    bonusAtributoFixo: { des: 2, car: 1 },
    bonusDesc: '+2 Destreza, +1 Carisma',
    idiomas: ['Comum', 'Halfling'],
    traços: [
      { nome: 'Sortudo (Lucky)', desc: 'Ao rolar um 1 natural no d20 (ataque, teste ou resistência), pode rerrolar o dado.' },
      { nome: 'Corajoso', desc: 'Vantagem em salvaguardas contra ficar com medo (amendrontado).' },
      { nome: 'Furtividade Natural', desc: 'Pode se esconder atrás de criaturas maiores que você.' },
    ],
    periciasConcedidas: [],
  },
  {
    id: 'draconato',
    nome: 'Draconato',
    nomeEn: 'Dragonborn',
    tag: 'SRD',
    icone: 'whatshot',
    tamanho: 'Médio',
    deslocamento: '30ft (9m)',
    deslocamentoNum: 30,
    visaoEscuro: false,
    bonusAtributoFixo: { for: 2, car: 1 },
    bonusDesc: '+2 Força, +1 Carisma',
    idiomas: ['Comum', 'Dracônico'],
    traços: [
      { nome: 'Arma de Sopro Elemental', desc: 'Exala uma rajada elemental destrutiva de 2d6 (cone ou linha) conforme ancestral dracônico.' },
      { nome: 'Resistência a Dano', desc: 'Resistência a dano do mesmo tipo elemental do seu sopro (Fogo, Gelo, Relâmpago, etc.).' },
    ],
    periciasConcedidas: [],
  },
  {
    id: 'gnomo',
    nome: 'Gnomo das Rochas',
    nomeEn: 'Rock Gnome',
    tag: 'SRD',
    icone: 'build',
    tamanho: 'Pequeno',
    deslocamento: '25ft (7.5m)',
    deslocamentoNum: 25,
    visaoEscuro: true,
    bonusAtributoFixo: { int: 2, con: 1 },
    bonusDesc: '+2 Inteligência, +1 Constituição',
    idiomas: ['Comum', 'Gnômico'],
    traços: [
      { nome: 'Esperteza Gnômica', desc: 'Vantagem em todas as salvaguardas de Inteligência, Sabedoria e Carisma contra magia.' },
      { nome: 'Engenhoquinheiro', desc: 'Pode construir pequenos dispositivos mecânicos (brinquedo, acendedor, caixa de música).' },
    ],
    periciasConcedidas: [],
  },
  {
    id: 'meio_elfo',
    nome: 'Meio-Elfo',
    nomeEn: 'Half-Elf',
    tag: 'SRD',
    icone: 'sentiment_very_satisfied',
    tamanho: 'Médio',
    deslocamento: '30ft (9m)',
    deslocamentoNum: 30,
    visaoEscuro: true,
    bonusAtributoFixo: { car: 2, des: 1, con: 1 },
    bonusDesc: '+2 Carisma e +1 em outros dois atributos à escolha',
    idiomas: ['Comum', 'Élfico', 'Um idioma adicional'],
    traços: [
      { nome: 'Versatilidade em Perícias', desc: 'Ganha proficiência em duas perícias quaisquer à sua escolha.' },
      { nome: 'Ancestralidade Feérica', desc: 'Vantagem contra ser enfeitiçado e imunidade a sono mágico.' },
      { nome: 'Visão no Escuro (60ft)', desc: 'Enxerga na escuridão até 18 metros.' },
    ],
    periciasConcedidas: [],
  },
  {
    id: 'meio_orc',
    nome: 'Meio-Orc',
    nomeEn: 'Half-Orc',
    tag: 'SRD',
    icone: 'fitness_center',
    tamanho: 'Médio',
    deslocamento: '30ft (9m)',
    deslocamentoNum: 30,
    visaoEscuro: true,
    bonusAtributoFixo: { for: 2, con: 1 },
    bonusDesc: '+2 Força, +1 Constituição',
    idiomas: ['Comum', 'Orc'],
    traços: [
      { nome: 'Resistência Implacável', desc: 'Ao ser reduzido a 0 PV mas não morto instantaneamente, fica com 1 PV (1x por descanso longo).' },
      { nome: 'Ataques Selvagens', desc: 'Em acertos críticos com armas corpo a corpo, rola um dado de dano extra da arma.' },
      { nome: 'Ameaçador', desc: 'Proficiência automática na perícia Intimidação.' },
    ],
    periciasConcedidas: ['intimidacao'],
  },
  {
    id: 'tiefling',
    nome: 'Tiefling',
    nomeEn: 'Tiefling',
    tag: 'SRD',
    icone: 'local_fire_department',
    tamanho: 'Médio',
    deslocamento: '30ft (9m)',
    deslocamentoNum: 30,
    visaoEscuro: true,
    bonusAtributoFixo: { car: 2, int: 1 },
    bonusDesc: '+2 Carisma, +1 Inteligência',
    idiomas: ['Comum', 'Infernal'],
    traços: [
      { nome: 'Resistência Infernal', desc: 'Resistência a dano de fogo permanente.' },
      { nome: 'Legado Infernal', desc: 'Conhece o truque Taumaturgia. No nível 3 ganha Repreensão Infernal e no nível 5 Escuridão.' },
      { nome: 'Visão no Escuro (60ft)', desc: 'Enxerga nas trevas até 18 metros.' },
    ],
    periciasConcedidas: [],
  },
  {
    id: 'aasimar',
    nome: 'Aasimar',
    nomeEn: 'Aasimar',
    tag: '2024',
    icone: 'auto_awesome',
    tamanho: 'Médio',
    deslocamento: '30ft (9m)',
    deslocamentoNum: 30,
    visaoEscuro: true,
    bonusAtributoFixo: { car: 2, sab: 1 },
    bonusDesc: '+2 Carisma, +1 Sabedoria',
    idiomas: ['Comum', 'Celestial'],
    traços: [
      { nome: 'Resistência Celestial', desc: 'Resistência a dano necrótico e dano radiante.' },
      { nome: 'Mãos Que Curam', desc: 'Com uma ação, toca uma criatura e restaura PV igual ao seu nível.' },
      { nome: 'Portador da Luz', desc: 'Conhece o truque Luz.' },
    ],
    periciasConcedidas: [],
  },
  {
    id: 'goliath',
    nome: 'Goliath',
    nomeEn: 'Goliath',
    tag: '2024',
    icone: 'landscape',
    tamanho: 'Médio',
    deslocamento: '30ft (9m)',
    deslocamentoNum: 30,
    visaoEscuro: false,
    bonusAtributoFixo: { for: 2, con: 1 },
    bonusDesc: '+2 Força, +1 Constituição',
    idiomas: ['Comum', 'Gigante'],
    traços: [
      { nome: 'Resistência da Pedra', desc: 'Pode reduzir 1d12 + mod Con do dano sofrido com uma reação.' },
      { nome: 'Constituição Poderosa', desc: 'Conta como uma categoria de tamanho maior para determinar capacidade de carga.' },
      { nome: 'Nascido na Montanha', desc: 'Aclimatação natural a altitudes elevadas e frio extremo.' },
      { nome: 'Atleta Nato', desc: 'Proficiência em Atletismo.' },
    ],
    periciasConcedidas: ['atletismo'],
  },
];

export const ANTECEDENTES_DND = [
  {
    id: 'acolito',
    nome: 'Acólito',
    nomeEn: 'Acolyte',
    tag: 'SRD',
    icone: 'temple_buddhist',
    pericias: ['intuicao', 'religiao'],
    ferramentas: 'Nenhuma',
    idiomas: 'Dois idiomas adicionais à escolha',
    caracteristica: {
      nome: 'Abrigo dos Fiéis',
      desc: 'Você e seus companheiros de aventura podem receber cura e cuidados gratuitos em templos dedicados à sua divindade.',
    },
    equipamento: 'Um símbolo sagrado, livro de preces, 5 varetas de incenso, vestimentas e 15 PO.',
    descricao: 'Você passou a juventude no serviço devoto de um templo de divindades, estudando ritos e acolhendo fiéis.',
  },
  {
    id: 'artesao_guilda',
    nome: 'Artesão de Guilda',
    nomeEn: 'Guild Artisan',
    tag: 'SRD',
    icone: 'handyman',
    pericias: ['intuicao', 'persuasao'],
    ferramentas: 'Um tipo de ferramenta de artesão',
    idiomas: 'Um idioma adicional',
    caracteristica: {
      nome: 'Membro da Guilda',
      desc: 'Como membro de guilda estabelecido, você tem hospedagem e suporte em qualquer filial de sua guilda.',
    },
    equipamento: 'Conjunto de ferramentas de artesão, carta de apresentação da guilda, roupas de viagem e 15 PO.',
    descricao: 'Você é um mestre em seu ofício, membro respeitado de uma corporação mercantil influente.',
  },
  {
    id: 'charlatao',
    nome: 'Charlatão',
    nomeEn: 'Charlatan',
    tag: 'SRD',
    icone: 'theater_comedy',
    pericias: ['enganacao', 'prestidigitacao'],
    ferramentas: 'Kit de Disfarce, Kit de Falsificação',
    idiomas: 'Nenhum',
    caracteristica: {
      nome: 'Identidade Falsa',
      desc: 'Você possui uma segunda identidade completa com documentos, disfarces e contatos para operar sem suspeitas.',
    },
    equipamento: 'Roupas finas, kit de disfarce, apetrechos de trapaça (dados viciados) e 15 PO.',
    descricao: 'Você sabe como manipular pessoas, vendendo ilusões, falsos milagres e promessas douradas.',
  },
  {
    id: 'criminoso',
    nome: 'Criminoso / Bandido',
    nomeEn: 'Criminal',
    tag: 'SRD',
    icone: 'lock_open',
    pericias: ['enganacao', 'furtividade'],
    ferramentas: 'Um conjunto de jogos, Ferramentas de Ladrão',
    idiomas: 'Nenhum',
    caracteristica: {
      nome: 'Contato Criminal',
      desc: 'Você possui um informante confiável e experiente no submundo do crime para obter mensagens e favores.',
    },
    equipamento: 'Um pé-de-cabra, roupas escuras comuns com capuz e 15 PO.',
    descricao: 'Você tem um histórico na ilegalidade, convivendo com guildas de ladrões, contrabandistas e assassinos.',
  },
  {
    id: 'eremita',
    nome: 'Eremita',
    nomeEn: 'Hermit',
    tag: 'SRD',
    icone: 'cabin',
    pericias: ['medicina', 'religiao'],
    ferramentas: 'Kit de Herbalismo',
    idiomas: 'Um idioma adicional',
    caracteristica: {
      nome: 'Descoberta Reveladora',
      desc: 'Seu isolamento concedeu uma revelação singular sobre um segredo do cosmos, uma ruína esquecida ou profecia.',
    },
    equipamento: 'Estojo de pergaminhos com anotações de estudo, cobertor de inverno, kit de herbalismo e 5 PO.',
    descricao: 'Você viveu em reclusão total nas montanhas, florestas ou mosteiros distantes em busca de iluminação.',
  },
  {
    id: 'forasteiro',
    nome: 'Forasteiro / Nômade',
    nomeEn: 'Outlander',
    tag: 'SRD',
    icone: 'explore',
    pericias: ['atletismo', 'sobrevivencia'],
    ferramentas: 'Um instrumento musical',
    idiomas: 'Um idioma adicional',
    caracteristica: {
      nome: 'Andarilho Nato',
      desc: 'Você possui memória perfeita para mapas e relevos geográficos e sempre encontra comida fresca e água para 6 pessoas.',
    },
    equipamento: 'Bordão, armadilha de caça, troféu de animal, roupas de viajante e 10 PO.',
    descricao: 'Você cresceu nos ermos selvagens longe da civilização, aprendendo a sobreviver em terras inóspitas.',
  },
  {
    id: 'heroi_povo',
    nome: 'Herói do Povo',
    nomeEn: 'Folk Hero',
    tag: 'SRD',
    icone: 'star',
    pericias: ['adestramento', 'sobrevivencia'],
    ferramentas: 'Um tipo de ferramenta de artesão, Veículos terrestres',
    idiomas: 'Nenhum',
    caracteristica: {
      nome: 'Hospitalidade Rústica',
      desc: 'O povo simples e plebeus o protegem de autoridades locais, oferecendo esconderijo e comida humilde.',
    },
    equipamento: 'Conjunto de ferramentas de artesão, pá, panela de ferro, roupas rústicas e 10 PO.',
    descricao: 'Você veio do povo simples e realizou um feito corajoso que inspirou sua vila contra a tirania.',
  },
  {
    id: 'marinheiro',
    nome: 'Marinheiro',
    nomeEn: 'Sailor',
    tag: 'SRD',
    icone: 'sailing',
    pericias: ['atletismo', 'percepcao'],
    ferramentas: 'Ferramentas de Navegador, Veículos aquáticos',
    idiomas: 'Nenhum',
    caracteristica: {
      nome: 'Passagem por Navio',
      desc: 'Você consegue viagem gratuita de navio para você e seu grupo em troca de trabalho a bordo.',
    },
    equipamento: 'Pino de amarração (clava), 15m de corda de seda, amuleto da sorte e 10 PO.',
    descricao: 'Você navegou em mares bravios em caravelas e galés, enfrentando tempestades e monstros oceânicos.',
  },
  {
    id: 'nobre',
    nome: 'Nobre',
    nomeEn: 'Noble',
    tag: 'SRD',
    icone: 'crown',
    pericias: ['historia', 'persuasao'],
    ferramentas: 'Um conjunto de jogos',
    idiomas: 'Um idioma adicional',
    caracteristica: {
      nome: 'Posição Privilegiada',
      desc: 'Graças ao seu sangue nobre, você é bem-vindo na alta sociedade e plebeus tratam você com deferência.',
    },
    equipamento: 'Roupas finas, anel de sinete, pergaminho de linhagem nobre e bolsa com 25 PO.',
    descricao: 'Você nasceu em berço de ouro entre castelos, brasões de família e intrigas cortesãs.',
  },
  {
    id: 'sabio',
    nome: 'Sábio / Erudito',
    nomeEn: 'Sage',
    tag: 'SRD',
    icone: 'school',
    pericias: ['arcanismo', 'historia'],
    ferramentas: 'Nenhuma',
    idiomas: 'Dois idiomas adicionais à escolha',
    caracteristica: {
      nome: 'Pesquisador de Tomos',
      desc: 'Ao buscar informações raras, se você não sabe a resposta, você quase sempre sabe onde e com quem encontrá-la.',
    },
    equipamento: 'Vidro de tinta preta, pena, faca pequena, carta com pergunta não respondida e 10 PO.',
    descricao: 'Você dedicou anos ao estudo de tomos empoeirados, bibliotecas arcanas e experimentos alquímicos.',
  },
  {
    id: 'soldado',
    nome: 'Soldado / Veterano',
    nomeEn: 'Soldier',
    tag: 'SRD',
    icone: 'military_tech',
    pericias: ['atletismo', 'intimidacao'],
    ferramentas: 'Veículos terrestres, Um conjunto de jogos',
    idiomas: 'Nenhum',
    caracteristica: {
      nome: 'Patente Militar',
      desc: 'Soldados e guardas reconhecem sua autoridade militar passada, cedendo acesso a fortalezas e guarnições.',
    },
    equipamento: 'Insígnia de patente, troféu de batalha de inimigo caído, baralho de cartas e 10 PO.',
    descricao: 'Você marchou nas linhas de frente de guerras sangrentas sob estandartes de exércitos temíveis.',
  },
];

export const POINT_BUY_COSTS = {
  8: 0,
  9: 1,
  10: 2,
  11: 3,
  12: 4,
  13: 5,
  14: 7,
  15: 9,
};

export const STANDARD_ARRAY = [15, 14, 13, 12, 10, 8];

export function calcularModificador(score) {
  return Math.floor((Number(score || 10) - 10) / 2);
}

export function formatarMod(n) {
  const num = Number(n) || 0;
  return num >= 0 ? `+${num}` : `${num}`;
}
